DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS person;

CREATE TABLE Person(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name VARCHAR(100) NOT NULL UNIQUE ,
                       year_of_birth INT NOT NULL
);

CREATE TABLE Book(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title VARCHAR(100) NOT NULL ,
                     author VARCHAR(100) NOT NULL ,
                     year_of_production INT NOT NULL,
                     person_id INT REFERENCES Person(id) ON DELETE SET NULL ,
                     take_at TIMESTAMP
);